// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrOlPJ8dBEw6OMxG6tXaILmAWYIvl4l8',
    appId: '1:671760916422:web:d6ccbe3fc49368426edcc7',
    messagingSenderId: '671760916422',
    projectId: 'socialmediaapp-ebf86',
    authDomain: 'socialmediaapp-ebf86.firebaseapp.com',
    storageBucket: 'socialmediaapp-ebf86.appspot.com',
    measurementId: 'G-NC3DGYE555',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9FYz6rMu3XUW9JDoPHdXTMW_BnUwPLg',
    appId: '1:671760916422:android:b1ee43eb40a595be6edcc7',
    messagingSenderId: '671760916422',
    projectId: 'socialmediaapp-ebf86',
    storageBucket: 'socialmediaapp-ebf86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcbWnKhIGRa6-CTcWW8MWOGlMaoa2VqC8',
    appId: '1:671760916422:ios:cc869b32203cac626edcc7',
    messagingSenderId: '671760916422',
    projectId: 'socialmediaapp-ebf86',
    storageBucket: 'socialmediaapp-ebf86.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcbWnKhIGRa6-CTcWW8MWOGlMaoa2VqC8',
    appId: '1:671760916422:ios:cc869b32203cac626edcc7',
    messagingSenderId: '671760916422',
    projectId: 'socialmediaapp-ebf86',
    storageBucket: 'socialmediaapp-ebf86.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQrOlPJ8dBEw6OMxG6tXaILmAWYIvl4l8',
    appId: '1:671760916422:web:deb7f737443e944a6edcc7',
    messagingSenderId: '671760916422',
    projectId: 'socialmediaapp-ebf86',
    authDomain: 'socialmediaapp-ebf86.firebaseapp.com',
    storageBucket: 'socialmediaapp-ebf86.appspot.com',
    measurementId: 'G-3N9Z7W4YQC',
  );
}
